### ISSUE TITLE
Kubernetes 1.29

### ISSUE THREAD

**Issue by sengi** [alphagov/govuk-infrastructure#1114]
We're currently on 1.28 but [1.29 is available for EKS](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-29/) now (since 23 Jan).

[EKS Release notes](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.29)

[k8s release announcement](https://kubernetes.io/blog/2023/12/13/kubernetes-v1-29-release/)

**Comment by nimalank7** [comment]
https://github.com/alphagov/govuk-helm-charts/pull/1894
https://github.com/alphagov/govuk-infrastructure/pull/1171
https://github.com/alphagov/govuk-infrastructure/pull/1170
https://github.com/alphagov/govuk-infrastructure/pull/1169
