### ISSUE TITLE
Run actionlint as a pre-merge check.

### ISSUE THREAD

**Issue by sengi** [alphagov/govuk-infrastructure#1243]
We have a bunch of reusable GitHub Actions workflows and actions in this repo. GitHub Actions is full of [footshooters](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections) so there's a lot of value in running a linter to catch common gotchas pre-merge.

https://github.com/rhysd/actionlint

**Comment by nimalank7** [comment]
See https://github.com/alphagov/govuk-infrastructure/pull/1312 for PR. Marking the issue as closed.
