### ISSUE TITLE
The way we're defining tfvars appears to defeat TFC's cost estimation.

### ISSUE THREAD

**Issue by sengi** [alphagov/govuk-infrastructure#1317]
Most of our instance counts and sizes etc. are specified in the tfc-configuration module, which then configures the vars in the TFC workspaces that run the root modules that actually manage stuff in AWS.

This appears to defeat Terraform Cloud's cost estimation feature on the very PRs where it would be most useful.

For example [this speculative plan](https://app.terraform.io/app/govuk/workspaces/tfc-configuration/runs/run-DJJ3pJGUCVKNdFhe) for https://github.com/alphagov/govuk-infrastructure/pull/1316 shows this, despite actually costing thousands:

> ## Plan finished
>
> Resources: 0 to add, 2 to change, 0 to destroy
>
> ## Cost estimation finished
>
> Resources: 0 of 159 estimated $0.00/mo +$0.00
>
> ### Too many resources to display
>
> Due to the large number of resources (159), we cannot show them in the browser.

**Comment by sengi** [comment]
Maybe just a bug to raise with Hashicorp/Broadcom tbh. Unless there's some better way we can do this configuration (but I'm pretty sure we're already doing they way they recommended!)

**Comment by nimalank7** [comment]
Odd as it sounds the HCP cost estimation is working correctly. According to [HCP documentation](https://developer.hashicorp.com/terraform/cloud-docs/cost-estimation/aws) these are the supported AWS resources that trigger cost estimation. Of these I focused on those which incurred costs and I searched through `govuk-infrastructure` to see where they were used.

| Resource      | Runs |
| ----------- | ----------- |
| `aws_cloudwatch_metric_alarm `     | https://app.terraform.io/app/govuk/workspaces/rds-integration/runs/run-K2kpaZur8CotPboU      |
| `aws_db_instance`   | https://app.terraform.io/app/govuk/workspaces/rds-integration/runs/run-K2kpaZur8CotPboU        |
| `aws_elasticache_cluster`   | https://app.terraform.io/app/govuk/workspaces/govuk-publishing-infrastructure-integration/runs/run-AkiFHMTHiLJR5oPi        |
| `aws_kms_key`   | [ecr](https://app.terraform.io/app/govuk/workspaces/ecr-production/runs/run-Ey41mJgfZUJRGJR1), [cluster-infrastructure](https://app.terraform.io/app/govuk/workspaces/cluster-infrastructure-integration/runs/run-Ff8HDubb9HacFmWB), [mobile-backend](https://app.terraform.io/app/govuk/workspaces/mobile-backend-integration/runs/run-pn6zRjoxDZBm3FBZ)        |

Looking at the runs you can see that cost estimation is working for these. In the [above example(https://app.terraform.io/app/govuk/workspaces/tfc-configuration/runs/run-DJJ3pJGUCVKNdFhe) open search isn't part of the supported AWS resources so no cost estimation is run. Another oddity is that though we spin up load balancers these won't come under cost estimation as they are managed by the AWS ALB controller whose terraform resource isn't a part of the supported list.

From this it sounds like the HCP cost estimation is of limited use. (Perhaps a better way would be to have something poll the AWS Billing API after a Terraform plan run)
